--- #YAML:1.0
name:               Dancer-Plugin-NYTProf
version:            0.04
abstract:           easy Devel::NYTProf profiling for Dancer apps
author:
    - David Precious <davidp@preshweb.co.uk>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Dancer:          1.306
    Devel::NYTProf:  0
    Test::More:      0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
