---
abstract: 'easy Devel::NYTProf profiling for Dancer apps'
author:
  - 'David Precious <davidp@preshweb.co.uk>'
build_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.82, CPAN::Meta::Converter version 2.120351'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dancer-Plugin-NYTProf
no_index:
  directory:
    - t
    - inc
requires:
  Capture::Tiny: 0
  Dancer: 1.306
  Devel::NYTProf: 0
  File::Temp: 0
  File::Which: 0
  File::stat: 0
  Test::More: 0
resources:
  bugtracker: https://github.com/bigpresh/Dancer-Plugin-NYTProf/issues
  license: http://dev.perl.org/licenses/
  repository: https://github.com/bigpresh/Dancer-Plugin-NYTProf.git
version: 0.50
